// <auto-generated />
using System;
using EntitySession01Ass.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntitySession01Ass.Migrations
{
    [DbContext(typeof(ITIDbContext))]
    [Migration("20250913180526_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntitySession01Ass.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Top_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Top_ID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Learn C# fundamentals",
                            Duration = 60,
                            Name = "C# Programming",
                            Top_ID = 1
                        },
                        new
                        {
                            ID = 2,
                            Description = "Database management",
                            Duration = 45,
                            Name = "SQL Server",
                            Top_ID = 2
                        },
                        new
                        {
                            ID = 3,
                            Description = "Web development",
                            Duration = 75,
                            Name = "ASP.NET Core",
                            Top_ID = 3
                        });
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Course_Inst", b =>
                {
                    b.Property<int>("inst_ID")
                        .HasColumnType("int");

                    b.Property<int>("course_ID")
                        .HasColumnType("int");

                    b.Property<string>("evaluate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("inst_ID", "course_ID");

                    b.HasIndex("course_ID");

                    b.ToTable("Course_Inst", (string)null);

                    b.HasData(
                        new
                        {
                            inst_ID = 1,
                            course_ID = 1,
                            evaluate = "Excellent course"
                        },
                        new
                        {
                            inst_ID = 2,
                            course_ID = 2,
                            evaluate = "Good material"
                        },
                        new
                        {
                            inst_ID = 3,
                            course_ID = 3,
                            evaluate = "Challenging but rewarding"
                        });
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("HiringDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Ins_ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Ins_ID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            HiringDate = new DateTime(2019, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Computer Science"
                        },
                        new
                        {
                            ID = 2,
                            HiringDate = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Information Technology"
                        },
                        new
                        {
                            ID = 3,
                            HiringDate = new DateTime(2022, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Software Engineering"
                        });
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Instructor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Bouns")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Dept_ID")
                        .HasColumnType("int");

                    b.Property<decimal?>("HourRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("Dept_ID");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Cairo",
                            Bouns = 2000.00m,
                            Dept_ID = 1,
                            HourRate = 50.00m,
                            Name = "Dr. Ahmed Ali",
                            Salary = 15000m
                        },
                        new
                        {
                            ID = 2,
                            Address = "Alexandria",
                            Bouns = 2500.00m,
                            Dept_ID = 1,
                            HourRate = 60.00m,
                            Name = "Prof. Mohamed Hassan",
                            Salary = 18000m
                        },
                        new
                        {
                            ID = 3,
                            Address = "Giza",
                            Bouns = 2200.00m,
                            Dept_ID = 2,
                            HourRate = 55.00m,
                            Name = "Dr. Sarah Smith",
                            Salary = 16000m
                        });
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Stud_Course", b =>
                {
                    b.Property<int>("stud_ID")
                        .HasColumnType("int");

                    b.Property<int>("course_ID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Grade")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("stud_ID", "course_ID");

                    b.HasIndex("course_ID");

                    b.ToTable("Stud_Course", (string)null);

                    b.HasData(
                        new
                        {
                            stud_ID = 1,
                            course_ID = 1,
                            Grade = 85.50m
                        },
                        new
                        {
                            stud_ID = 1,
                            course_ID = 2,
                            Grade = 90.00m
                        },
                        new
                        {
                            stud_ID = 2,
                            course_ID = 1,
                            Grade = 78.00m
                        },
                        new
                        {
                            stud_ID = 3,
                            course_ID = 3,
                            Grade = 92.50m
                        });
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("Dep_Id")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Dep_Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Cairo",
                            Age = 20,
                            Dep_Id = 1,
                            FName = "John",
                            LName = "Doe"
                        },
                        new
                        {
                            ID = 2,
                            Address = "Alexandria",
                            Age = 21,
                            Dep_Id = 1,
                            FName = "Jane",
                            LName = "Smith"
                        },
                        new
                        {
                            ID = 3,
                            Address = "Giza",
                            Age = 22,
                            Dep_Id = 2,
                            FName = "Mike",
                            LName = "Johnson"
                        });
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Topic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Programming"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Database"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Web Development"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Networking"
                        });
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Course", b =>
                {
                    b.HasOne("EntitySession01Ass.Models.Topic", "Topic")
                        .WithMany("Courses")
                        .HasForeignKey("Top_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Course_Inst", b =>
                {
                    b.HasOne("EntitySession01Ass.Models.Course", "Course")
                        .WithMany("CourseInstructors")
                        .HasForeignKey("course_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntitySession01Ass.Models.Instructor", "Instructor")
                        .WithMany("CourseInstructors")
                        .HasForeignKey("inst_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Department", b =>
                {
                    b.HasOne("EntitySession01Ass.Models.Instructor", "Manager")
                        .WithMany()
                        .HasForeignKey("Ins_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Instructor", b =>
                {
                    b.HasOne("EntitySession01Ass.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("Dept_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Stud_Course", b =>
                {
                    b.HasOne("EntitySession01Ass.Models.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("course_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntitySession01Ass.Models.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("stud_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Student", b =>
                {
                    b.HasOne("EntitySession01Ass.Models.Department", null)
                        .WithMany("Students")
                        .HasForeignKey("Dep_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Course", b =>
                {
                    b.Navigation("CourseInstructors");

                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Department", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Instructor", b =>
                {
                    b.Navigation("CourseInstructors");
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Student", b =>
                {
                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("EntitySession01Ass.Models.Topic", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
